[project]
name = "linox"
description = "Linear operators in JAX."
readme = "README.md"
requires-python = ">=3.10"
dynamic = ["version"]

authors = [
  { name = "Tobias Weber", email = "t.weber@uni-tuebingen.de" },
  { name = "Lenard Rommel", email = "lenardrommel@icloud.com" },
]

keywords = ["Linear operators", "Operators", "Matrix-free linear algebra"]

classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Science/Research",
  "Topic :: Scientific/Engineering :: Artificial Intelligence",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3 :: Only",
  "Operating System :: OS Independent",
]

dependencies = [
  "jax",
  "plum-dispatch",
  "numpy",
  "scipy",
  "jaxtyping",
  "matplotlib",
  "tueplots",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["linox*", "helper*"]
exclude = ["site*", "tests*", "docs*"]


# Optional: keep these for "pip install linox[docs]" etc when you publish (extras are public API)
[project.optional-dependencies]
docs = ["mkdocs-material", "mkdocstrings[python]"]
test = ["pytest", "pytest-cov", "pytest-cases", "hypothesis", "tox-uv"]
dev = ["pre-commit", "pyright", "jupyterlab", "isort>=7.0.0", "ruff"]

[dependency-groups]
lint = ["ruff>=0.15.0"]


test = [
  "pytest",
  "pytest-cov",
  "pytest-cases",
  "hypothesis",
  "tox-uv",
]

docs = [
  "mkdocs-material",
  "mkdocstrings[python]",
]

dev = [
  { include-group = "lint" },
  { include-group = "test" },
  { include-group = "docs" },
  "pre-commit",
  "pyright",
  "jupyterlab",
  "isort>=7.0.0",
]

[tool.uv]
default-groups = ["dev"]

[tool.ruff]
line-length = 150
exclude = ["tests"]


[tool.ruff.lint]
select = ["E", "F", "I", "D", "UP", "B", "SIM", "RUF"]

ignore = [
  "D107",  # Missing docstring in __init__
  "D105",  # Missing docstring in magic method
  "RUF002", # Docstring contains ambiguous sign
  "RUF003", # Comment contains ambiguous sign
  "E741", # Ambiguous variable name
  "D401", # Docstring not in imperative mood
]
[tool.ruff.lint.pydocstyle]
convention = "numpy"
[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["D", "E741"]

